import "./globals.css";
import NavBar from "@/components/NavBar";


export const metadata = {
  title: "My Blog Site",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar/>
        <div  style={{"paddingTop" : "20px"}} >
          {children}
        </div>
      </body>
    </html>
  );
}
